// SPDX-License-Identifier: Apache-2.0
// The regression test for the incident that started this project.
//
// Two terminals shared one Markdown file for live status. One agent read it,
// appended, wrote it back, and destroyed about 128 lines of the other agent's
// work. This test reproduces that failure with the naive approach, then proves
// the same traffic through Agent Fridge loses nothing.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { bootstrap, cleanup, fridge, notes } from '../helpers.mjs';
import { race } from './race.mjs';

const AGENTS = 8;
const LINES = 25;
const names = Array.from({ length: AGENTS }, (_, i) => `writer-${String(i).padStart(2, '0')}`);

test('the old way really does lose lines (this is the bug, reproduced)', async () => {
  const root = bootstrap('lossy', names);
  const shared = path.join(root, 'shared-development-updates.md');
  try {
    fs.writeFileSync(shared, '# Live updates\n');
    const results = await race(root, 'race-write.mjs', names.map((a) => ({
      FRIDGE_ACTOR: a, WRITE_MODE: 'shared-file', SHARED_FILE: shared, WRITE_COUNT: String(LINES),
    })));
    assert.equal(results.every((r) => r.report?.written === LINES), true, 'every process believed it wrote every line');

    const survived = fs.readFileSync(shared, 'utf8').split('\n').filter((l) => l.startsWith('- ')).length;
    const attempted = AGENTS * LINES;
    assert.ok(survived < attempted, `expected lost lines with the naive approach, but all ${attempted} survived`);
    // Kept as a printed fact rather than a strict bound: the amount lost depends
    // on scheduling. The point is that it is never zero.
    console.log(`      shared-file approach: ${attempted} lines written, ${survived} survived, ${attempted - survived} lost`);
  } finally { cleanup(root); }
});

test('nobody erases the door: every note from every process survives', async () => {
  const root = bootstrap('lossless', names);
  try {
    const results = await race(root, 'race-write.mjs', names.map((a) => ({
      FRIDGE_ACTOR: a, WRITE_MODE: 'fridge', WRITE_COUNT: String(LINES),
    })));
    assert.equal(results.every((r) => r.report?.written === LINES), true, 'every process reported success');

    const pinned = notes(root).filter((n) => n.type === 'note.note');
    assert.equal(pinned.length, AGENTS * LINES, `expected ${AGENTS * LINES} notes, found ${pinned.length}`);
    assert.equal(new Set(pinned.map((n) => n.id)).size, pinned.length, 'no duplicate ids');

    for (const a of names) {
      const mine = pinned.filter((n) => n.actorName === a);
      assert.equal(mine.length, LINES, `${a} lost notes`);
      for (let i = 0; i < LINES; i++) {
        assert.equal(mine.filter((n) => n.summary === `${a} line ${i}`).length, 1, `${a} line ${i} is missing or duplicated`);
      }
    }
    console.log(`      fridge approach:      ${AGENTS * LINES} notes written, ${pinned.length} survived, 0 lost`);
  } finally { cleanup(root); }
});

test('every note file has exactly one writer and is never rewritten', async () => {
  const root = bootstrap('write-once', names.slice(0, 4));
  try {
    await race(root, 'race-write.mjs', names.slice(0, 4).map((a) => ({
      FRIDGE_ACTOR: a, WRITE_MODE: 'fridge', WRITE_COUNT: '10',
    })));
    const base = path.join(root, '.fridge', 'notes');
    const files = [];
    const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p); else files.push(p); } };
    walk(base);
    for (const f of files) {
      const record = JSON.parse(fs.readFileSync(f, 'utf8'));
      assert.ok(path.basename(f).includes(record.id), 'the filename embeds its own id, so two writers cannot pick the same name');
      assert.ok(record.actorName, 'every note names its author');
    }
    const before = files.map((f) => fs.statSync(f).mtimeMs);
    fridge(root, ['pin', 'one more'], { actor: names[0] });
    const after = files.map((f) => fs.statSync(f).mtimeMs);
    assert.deepEqual(after, before, 'writing a new note never touches an existing one');
  } finally { cleanup(root); }
});

test('the generated door survives concurrent writers and stays parseable', async () => {
  const root = bootstrap('door-race', names);
  try {
    await race(root, 'race-write.mjs', names.map((a) => ({ FRIDGE_ACTOR: a, WRITE_MODE: 'fridge', WRITE_COUNT: '10' })));
    const door = fs.readFileSync(path.join(root, '.fridge', 'DOOR.md'), 'utf8');
    assert.match(door, /^<!-- GENERATED by agent-fridge/, 'the door is complete, not a torn half-write');
    assert.match(door, /DO NOT EDIT/);
    assert.equal(fridge(root, ['render'], { actor: names[0] }).code, 0);
    assert.equal(fridge(root, ['board', '--check'], { actor: names[0] }).code, 0);
  } finally { cleanup(root); }
});
