// SPDX-License-Identifier: Apache-2.0
// One canonical rule text. Every vendor file gets the same block inside markers,
// so there is exactly one source of truth and drift is detectable.
package adapters

import (
	"path/filepath"
	"regexp"
	"strings"

	"github.com/RagnarPitla/agent-fridge/internal/brand"
	"github.com/RagnarPitla/agent-fridge/internal/errs"
	"github.com/RagnarPitla/agent-fridge/internal/fsx"
	"github.com/RagnarPitla/agent-fridge/internal/util"
)

// BeginRE matches the generated block header and captures its body hash.
var BeginRE = regexp.MustCompile(`<!-- BEGIN WCP-ADAPTER v0\.1 hash:([0-9a-f]{12}) -->`)

// End closes a generated block.
const End = "<!-- END WCP-ADAPTER v0.1 -->"

// Vendor is one target instruction file.
type Vendor struct {
	Key   string
	File  string
	Label string
}

// Order is the stable vendor order used by every listing.
var Order = []string{"agents", "claude", "copilot", "codex", "cursor", "generic"}

// Vendors maps a vendor key to its target file.
var Vendors = map[string]Vendor{
	"agents":  {"agents", "AGENTS.md", "AGENTS.md (Codex, Copilot CLI, Amp, and anything that reads AGENTS.md)"},
	"claude":  {"claude", "CLAUDE.md", "Claude Code"},
	"copilot": {"copilot", filepath.Join(".github", "copilot-instructions.md"), "GitHub Copilot (IDE and CLI)"},
	"codex":   {"codex", filepath.Join(".codex", "instructions.md"), "OpenAI Codex (explicit file)"},
	"cursor":  {"cursor", filepath.Join(".cursor", "rules", "agent-fridge.mdc"), "Cursor"},
	"generic": {"generic", filepath.Join("docs", "AGENT-COORDINATION.md"), "Generic / any other tool"},
}

// Body is the canonical rule text. Deliberately short: agents that read 25
// lines follow 25 lines.
var Body = strings.Join([]string{
	"## Shared fridge: how we avoid erasing each other",
	"",
	"This repository may have more than one agent or human working in it at the same time.",
	"The fridge door is the shared board. Everybody pins their own note. Nobody edits anybody",
	"else's note. State lives in `" + brand.StateDir + "/`; `" + brand.StateDir + "/DOOR.md` is a generated view, never edit it.",
	"",
	"Before you edit files:",
	"",
	"```sh",
	brand.Bin + ` join --agent "<your-name>" --vendor "<claude|copilot|codex|human|other>"   # once per session`,
	brand.Bin + ` claim "<path-or-glob>" --task "<what you are doing>" --ttl 30m            # take the chore`,
	"```",
	"",
	"If `" + brand.Bin + " claim` exits **10**, somebody else already has that chore. Do not edit those paths.",
	"Read `" + brand.Bin + " board`, then either claim different paths, `" + brand.Bin + " wait <claim-id>`, or ask via",
	"`" + brand.Bin + " handoff <claim-id> --to <them> --note \"...\"`. Never work around a conflict by editing anyway.",
	"",
	"While you work:",
	"",
	"```sh",
	brand.Bin + " check <path>...            # exit 0 mine, 10 theirs, 14 unclaimed",
	brand.Bin + " heartbeat                  # \"still on it\" - renews your lease",
	brand.Bin + " pin \"what just happened\"   # durable note, write-once, never overwrites anyone",
	brand.Bin + " release <claim-id> --outcome done --note \"what changed\"",
	"```",
	"",
	"Rules:",
	"",
	"1. Do not hand-edit anything under `" + brand.StateDir + "/` and do not edit `" + brand.StateDir + "/DOOR.md`.",
	"2. Do not use `--force` to take somebody else's card unless a human told you to.",
	"3. Claim the narrowest paths that cover your work, and release when you stop.",
	"4. Report progress with `" + brand.Bin + " pin`, not by editing a shared Markdown file.",
	"",
	"Full protocol: `" + brand.StateDir + "/` and https://github.com/RagnarPitla/" + brand.Package + " (protocol " + brand.Protocol + ").",
}, "\n")

// BodyHash identifies the canonical text currently shipped.
func BodyHash() string { return util.ShortHash(Body) }

// Block is the full generated block, markers included.
func Block() string {
	return "<!-- BEGIN WCP-ADAPTER v0.1 hash:" + BodyHash() + " -->\n" +
		"<!-- Generated by `" + brand.Bin + " adapters install`. Edit the protocol, not this block. -->\n" +
		Body + "\n" + End
}

// Splice inserts the block into an existing document without touching a byte
// of the rest.
func Splice(current, next string) (string, error) {
	if current == "" {
		return next + "\n", nil
	}
	begin := BeginRE.FindString(current)
	if begin == "" {
		sep := "\n\n"
		if strings.HasSuffix(current, "\n") {
			sep = "\n"
		}
		return current + sep + next + "\n", nil
	}
	start := strings.Index(current, begin)
	endIdx := strings.Index(current[start:], End)
	if endIdx == -1 {
		return "", errs.New("E_STATE_CORRUPT", "Found a start marker with no matching end marker.").
			WithHint("Delete the partial block by hand, then re-run: fridge adapters install")
	}
	endIdx += start
	return current[:start] + next + current[endIdx+len(End):], nil
}

// Status describes one vendor file.
type Status struct {
	Vendor    string
	File      string
	AbsPath   string
	Label     string
	State     string
	FoundHash string
	WantHash  string
	Action    string
}

// StatusFor inspects one vendor file.
func StatusFor(root, vendorKey string) Status {
	v := Vendors[vendorKey]
	file := filepath.Join(root, v.File)
	current, ok := fsx.ReadTextOr(file)
	found := ""
	if ok {
		if m := BeginRE.FindStringSubmatch(current); m != nil {
			found = m[1]
		}
	}
	state := "missing"
	switch {
	case !ok:
		state = "missing"
	case found == "":
		state = "absent"
	case found == BodyHash():
		state = "current"
	default:
		state = "drifted"
	}
	return Status{Vendor: vendorKey, File: v.File, AbsPath: file, Label: v.Label,
		State: state, FoundHash: found, WantHash: BodyHash()}
}

// Install writes or checks the block for each vendor.
func Install(root string, vendorKeys []string, check bool, tmpDir string) ([]Status, error) {
	results := []Status{}
	for _, key := range vendorKeys {
		if _, ok := Vendors[key]; !ok {
			return nil, errs.New("E_USAGE", "Unknown vendor '"+key+"'.").
				WithHint("Known: " + strings.Join(Order, ", "))
		}
		st := StatusFor(root, key)
		if !check && st.State != "current" {
			if err := fsx.EnsureDir(filepath.Dir(st.AbsPath)); err != nil {
				return nil, err
			}
			current, _ := fsx.ReadTextOr(st.AbsPath)
			next, err := Splice(current, Block())
			if err != nil {
				return nil, err
			}
			if err := fsx.WriteAtomic(st.AbsPath, next, tmpDir); err != nil {
				return nil, err
			}
			switch st.State {
			case "missing":
				st.Action = "created"
			case "absent":
				st.Action = "appended"
			default:
				st.Action = "updated"
			}
		} else if check {
			st.Action = "checked"
		} else {
			st.Action = "unchanged"
		}
		results = append(results, st)
	}
	return results, nil
}
