// SPDX-License-Identifier: Apache-2.0
// One canonical rule text. Every vendor file gets the same block inside markers,
// so there is exactly one source of truth and drift is detectable.
import fs from 'node:fs';
import path from 'node:path';
import { AppError } from '../core/errors.mjs';
import { ensureDir, writeAtomic } from '../core/fsx.mjs';
import { shortHash } from '../core/util.mjs';
import { BIN, PACKAGE, PROTOCOL, STATE_DIR } from '../brand.mjs';

export const BEGIN_RE = /<!-- BEGIN WCP-ADAPTER v0\.1 hash:([0-9a-f]{12}) -->/;
export const END = '<!-- END WCP-ADAPTER v0.1 -->';

export const VENDORS = {
  agents: { file: 'AGENTS.md', label: 'AGENTS.md (Codex, Copilot CLI, Amp, and anything that reads AGENTS.md)' },
  claude: { file: 'CLAUDE.md', label: 'Claude Code' },
  copilot: { file: path.join('.github', 'copilot-instructions.md'), label: 'GitHub Copilot (IDE and CLI)' },
  codex: { file: path.join('.codex', 'instructions.md'), label: 'OpenAI Codex (explicit file)' },
  cursor: { file: path.join('.cursor', 'rules', 'fridgeboard.mdc'), label: 'Cursor' },
  generic: { file: path.join('docs', 'AGENT-COORDINATION.md'), label: 'Generic / any other tool' },
};

/** The canonical rules. Deliberately short: agents that read 25 lines follow 25 lines. */
export const BODY = [
  '## Shared fridge: how we avoid erasing each other',
  '',
  'This repository may have more than one agent or human working in it at the same time.',
  'The fridge door is the shared board. Everybody pins their own note. Nobody edits anybody',
  `else's note. State lives in \`${STATE_DIR}/\`; \`${STATE_DIR}/DOOR.md\` is a generated view, never edit it.`,
  '',
  'Before you edit files:',
  '',
  '```sh',
  `${BIN} join --agent "<your-name>" --vendor "<claude|copilot|codex|human|other>"   # once per session`,
  `${BIN} claim "<path-or-glob>" --task "<what you are doing>" --ttl 30m            # take the chore`,
  '```',
  '',
  `If \`${BIN} claim\` exits **10**, somebody else already has that chore. Do not edit those paths.`,
  `Read \`${BIN} board\`, then either claim different paths, \`${BIN} wait <claim-id>\`, or ask via`,
  `\`${BIN} handoff <claim-id> --to <them> --note "..."\`. Never work around a conflict by editing anyway.`,
  '',
  'While you work:',
  '',
  '```sh',
  `${BIN} check <path>...            # exit 0 mine, 10 theirs, 14 unclaimed`,
  `${BIN} heartbeat                  # "still on it" - renews your lease`,
  `${BIN} pin "what just happened"   # durable note, write-once, never overwrites anyone`,
  `${BIN} release <claim-id> --outcome done --note "what changed"`,
  '```',
  '',
  'Rules:',
  '',
  '1. Do not hand-edit anything under `' + STATE_DIR + '/` and do not edit `' + STATE_DIR + '/DOOR.md`.',
  '2. Do not use `--force` to take somebody else\'s card unless a human told you to.',
  '3. Claim the narrowest paths that cover your work, and release when you stop.',
  '4. Report progress with `' + BIN + ' pin`, not by editing a shared Markdown file.',
  '',
  `Full protocol: \`${STATE_DIR}/\` and https://github.com/RagnarPitla/${PACKAGE} (protocol ${PROTOCOL}).`,
].join('\n');

export const bodyHash = () => shortHash(BODY);

export function block() {
  const hash = bodyHash();
  return `<!-- BEGIN WCP-ADAPTER v0.1 hash:${hash} -->\n<!-- Generated by \`${BIN} adapters install\`. Edit the protocol, not this block. -->\n${BODY}\n${END}`;
}

/** Splice the block into an existing document without touching a byte of the rest. */
export function splice(current, next) {
  if (!current) return `${next}\n`;
  const begin = current.match(BEGIN_RE);
  if (!begin) {
    const sep = current.endsWith('\n') ? '\n' : '\n\n';
    return `${current}${sep}${next}\n`;
  }
  const start = current.indexOf(begin[0]);
  const endIdx = current.indexOf(END, start);
  if (endIdx === -1) {
    throw new AppError('E_STATE_CORRUPT', 'Found a start marker with no matching end marker.', {
      hint: 'Delete the partial block by hand, then re-run: fridge adapters install',
    });
  }
  return current.slice(0, start) + next + current.slice(endIdx + END.length);
}

export function statusFor(root, vendorKey) {
  const v = VENDORS[vendorKey];
  const file = path.join(root, v.file);
  let current = null;
  try { current = fs.readFileSync(file, 'utf8'); } catch { current = null; }
  const found = current ? current.match(BEGIN_RE) : null;
  const state = current === null ? 'missing' : !found ? 'absent' : found[1] === bodyHash() ? 'current' : 'drifted';
  return { vendor: vendorKey, file: v.file, absPath: file, label: v.label, state, foundHash: found?.[1] || null, wantHash: bodyHash() };
}

export function install(root, vendorKeys, { check = false, tmpDir } = {}) {
  const results = [];
  for (const key of vendorKeys) {
    if (!VENDORS[key]) {
      throw new AppError('E_USAGE', `Unknown vendor '${key}'.`, { hint: `Known: ${Object.keys(VENDORS).join(', ')}` });
    }
    const st = statusFor(root, key);
    if (!check && st.state !== 'current') {
      ensureDir(path.dirname(st.absPath));
      let current = null;
      try { current = fs.readFileSync(st.absPath, 'utf8'); } catch { current = null; }
      writeAtomic(st.absPath, splice(current, block()), tmpDir);
      st.action = st.state === 'missing' ? 'created' : st.state === 'absent' ? 'appended' : 'updated';
    } else {
      st.action = check ? 'checked' : 'unchanged';
    }
    results.push(st);
  }
  return results;
}
