// SPDX-License-Identifier: Apache-2.0
// The door is a generated view. It is never the source of truth, and never hand-edited.
import { humanMs, shortHash, stableStringify } from './util.mjs';
import { listClaims, readNotes } from './store.mjs';
import { listJson, writeAtomic } from './fsx.mjs';
import { PACKAGE, VERSION } from '../brand.mjs';

export const seams = {
  afterAutoWrite: () => {},
};

const pad = (s, n) => String(s).padEnd(n);
const cut = (s, n) => (String(s).length > n ? String(s).slice(0, n - 1) + '~' : String(s));

export function snapshot(ws) {
  const all = listClaims(ws, { tolerateCorrupt: true });
  const claims = all.filter((d) => !d.stale);
  const queue = listJson(ws.paths.queue).length;
  return {
    workspaceId: ws.config.workspaceId,
    generatedAt: new Date().toISOString(),
    corrupt: all.corrupt ? [...all.corrupt] : [],
    claims: claims.map((d) => ({
      id: d.claim.id,
      actorName: d.claim.actorName,
      vendor: d.claim.vendor,
      mode: d.claim.mode,
      task: d.claim.task,
      include: d.claim.scope.include,
      exclude: d.claim.scope.exclude,
      files: d.claim.scope.materialized.length,
      branch: d.claim.labels?.branch || null,
      expiresAt: d.effectiveExpiresAt,
      expiresInMs: d.expiresInMs,
      pid: d.claim.process?.pid ?? null,
      state: d.claim.state,
    })),
    waiting: queue,
    notes: readNotes(ws, { limit: 5 }).map((n) => ({ ts: n.ts, actorName: n.actorName, type: n.type, summary: n.summary })),
  };
}

/** A hash of everything that matters, with wall-clock noise removed, so that
 *  `--check` answers "is this view stale?" and not "did a second pass?". */
export function stateKeyOf(s) {
  return shortHash(stableStringify({
    workspaceId: s.workspaceId,
    waiting: s.waiting,
    corrupt: s.corrupt || [],
    claims: s.claims.map((c) => ({ ...c, expiresInMs: undefined })),
    notes: s.notes,
  }));
}

export const stateKey = (ws) => stateKeyOf(snapshot(ws));

export const STATE_KEY_RE = /state:([0-9a-f]{12})/;

/** Drift is decided by the recorded state key, never by diffing rendered text. */
export function doorDrift(ws, text) {
  const found = typeof text === 'string' ? text.match(STATE_KEY_RE) : null;
  const want = stateKey(ws);
  return { drift: !found || found[1] !== want, found: found?.[1] || null, want };
}

// One snapshot in, one document out. Taking a second snapshot for the hash
// lets a claim appear between the two, and then the stamp certifies a body
// that was never rendered: `--check` passes on a door that is already wrong.
export function renderDoorFrom(s) {
  const lines = [];
  lines.push(`<!-- GENERATED by ${PACKAGE} ${VERSION} at ${s.generatedAt} state:${stateKeyOf(s)}`);
  lines.push('     Source of truth: .fridge/. DO NOT EDIT. Regenerate with: fridge render -->');
  lines.push('# The door');
  lines.push('');
  lines.push(`Fridge \`${s.workspaceId}\` | ${s.claims.length} chore(s) claimed | ${s.waiting} waiting`);
  lines.push('');
  if (s.corrupt?.length) {
    lines.push(`> **${s.corrupt.length} card(s) are unreadable, so this door is incomplete.** Paths that look free may not be.`);
    for (const f of s.corrupt) lines.push(`> - \`${f}\``);
    lines.push('>');
    lines.push('> Fix with: `fridge doctor --fix`');
    lines.push('');
  }
  lines.push('## Claimed right now');
  lines.push('');
  if (!s.claims.length) lines.push('Nothing is claimed. The door is clear.');
  else {
    lines.push('| Card | Who | Mode | Scope | Doing | Back by |');
    lines.push('|---|---|---|---|---|---|');
    for (const c of s.claims) {
      lines.push(`| \`${c.id}\` | ${c.actorName} (${c.vendor}) | ${c.mode} | ${c.include.map((p) => `\`${p}\``).join(', ')} | ${c.task || '-'} | in ${humanMs(c.expiresInMs)} |`);
    }
  }
  lines.push('');
  lines.push('## Last 5 notes');
  lines.push('');
  if (!s.notes.length) lines.push('No notes pinned yet.');
  else for (const n of s.notes) lines.push(`- ${n.ts} ${n.actorName} \`${n.type}\` ${n.summary}`);
  lines.push('');
  return lines.join('\n');
}

export const renderDoor = (ws) => renderDoorFrom(snapshot(ws));

export function renderStatusText(ws, { mine = null, wide = false } = {}) {
  const s = snapshot(ws);
  const claims = mine ? s.claims.filter((c) => c.actorName === mine) : s.claims;
  const out = [];
  out.push(`fridge ${s.workspaceId}  ${claims.length} claimed  ${s.waiting} waiting`);
  out.push('');
  if (s.corrupt?.length) {
    out.push(`WARNING: ${s.corrupt.length} card(s) are unreadable, so ownership is unknown.`);
    for (const f of s.corrupt) out.push(`  ${f}`);
    out.push('  Paths that look free may not be. Run: fridge doctor --fix');
    out.push('');
  }
  if (!claims.length) {
    out.push('Nothing is claimed. The door is clear.');
  } else {
    const w = wide ? 40 : 24;
    out.push(`${pad('CARD', 32)}${pad('WHO', 16)}${pad('MODE', 10)}${pad('SCOPE', w)}${pad('BACK BY', 10)}TASK`);
    for (const c of claims) {
      out.push(
        pad(c.id, 32) + pad(cut(c.actorName, 15), 16) + pad(c.mode, 10)
        + pad(cut(c.include.join(','), w - 1), w) + pad(humanMs(c.expiresInMs), 10) + cut(c.task || '-', wide ? 80 : 40),
      );
    }
  }
  if (s.notes.length) {
    out.push('');
    out.push('recent notes:');
    for (const n of s.notes) out.push(`  ${n.ts}  ${pad(cut(n.actorName, 14), 15)} ${pad(n.type, 18)} ${cut(n.summary, 70)}`);
  }
  return out.join('\n');
}

/** The door is cheap to regenerate, so keep it fresh after anything that changes state. */
export function autoRender(ws) {
  if (!ws.config?.door?.autoRender) return false;
  try {
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const captured = snapshot(ws);
      writeAtomic(ws.paths.door, renderDoorFrom(captured), ws.paths.tmp);
      seams.afterAutoWrite(ws, attempt);
      if (stateKey(ws) === stateKeyOf(captured)) return true;
    }
    return false;
  } catch {
    return false; // a stale view must never fail a real operation
  }
}
