// SPDX-License-Identifier: Apache-2.0
package render

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/RagnarPitla/agent-fridge/internal/store"
)

func newWorkspace(t *testing.T) *store.Workspace {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not locate go.mod")
		}
		dir = parent
	}
	root := filepath.Join(dir, ".scratch", "gotest", "render-"+strings.ReplaceAll(t.Name(), "/", "_"))
	if err := os.RemoveAll(root); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "src", "api"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "src", "api", "routes.ts"), []byte("x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(root) })
	ws, _, err := store.Init(root, false)
	if err != nil {
		t.Fatal(err)
	}
	return ws
}

func TestDoorIsDeterministicApartFromItsTimestamp(t *testing.T) {
	ws := newWorkspace(t)
	strip := func(doc string) string {
		out := []string{}
		for _, line := range strings.Split(doc, "\n") {
			if strings.Contains(line, "GENERATED by") || strings.Contains(line, "generated ") {
				continue
			}
			out = append(out, line)
		}
		return strings.Join(out, "\n")
	}
	if strip(Door(ws)) != strip(Door(ws)) {
		t.Errorf("two renders of unchanged state disagree")
	}
	if StateKey(ws) != StateKey(ws) {
		t.Errorf("the state key is not stable across calls")
	}
}

// The state key must ignore wall-clock countdown fields, or every render would
// look drifted a millisecond later.
func TestDriftIsDecidedByTheStateKey(t *testing.T) {
	ws := newWorkspace(t)
	doc := Door(ws)
	drift, found, want := Drift(ws, doc)
	if drift {
		t.Errorf("a freshly rendered door reports drift (%s vs %s)", found, want)
	}
	if drift, _, _ := Drift(ws, "no marker here"); !drift {
		t.Errorf("a view with no state marker must count as drifted")
	}
	if drift, _, _ := Drift(ws, "state:000000000000"); !drift {
		t.Errorf("a stale state marker must count as drifted")
	}
}

func TestDoorCarriesTheGeneratedWarning(t *testing.T) {
	ws := newWorkspace(t)
	doc := Door(ws)
	for _, want := range []string{"GENERATED by", "DO NOT EDIT", "# The door", "Claimed right now"} {
		if !strings.Contains(doc, want) {
			t.Errorf("door is missing %q", want)
		}
	}
	if !StateKeyRE.MatchString(doc) {
		t.Errorf("door has no state marker")
	}
}

func TestStatusTextIsASCIIAndAligned(t *testing.T) {
	ws := newWorkspace(t)
	text := StatusText(ws, "", false)
	for i, r := range text {
		if r > 127 {
			t.Fatalf("non-ASCII rune %q at byte %d of the status view", r, i)
		}
	}
	if !strings.Contains(text, "nothing is claimed") && !strings.Contains(text, "claimed") {
		t.Errorf("unexpected empty-state text:\n%s", text)
	}
}

func TestSnapshotShapeIsStable(t *testing.T) {
	ws := newWorkspace(t)
	s := Snapshot(ws)
	// Exactly the keys src/core/render.mjs emits, no more and no fewer:
	// views/status.json is consumed by both implementations.
	want := []string{"claims", "generatedAt", "notes", "waiting", "workspaceId"}
	for _, key := range want {
		if _, ok := s[key]; !ok {
			t.Errorf("snapshot is missing %q", key)
		}
	}
	if len(s) != len(want) {
		t.Errorf("snapshot has %d keys, want %d: %v", len(s), len(want), s)
	}
	if s.Str("workspaceId") == "" {
		t.Errorf("snapshot has no workspace id")
	}
}

func TestAutoRendersOnlyWhenConfigured(t *testing.T) {
	ws := newWorkspace(t)
	if !Auto(ws) {
		t.Fatalf("autoRender defaults to on, so Auto should have written the door")
	}
	doc, ok := os.ReadFile(ws.Paths.Door)
	_ = doc
	if ok != nil {
		t.Fatalf("Auto did not write DOOR.md: %v", ok)
	}
	ws.Config.Set("door.autoRender", false)
	if Auto(ws) {
		t.Errorf("Auto must respect door.autoRender=false")
	}
}
