// SPDX-License-Identifier: Apache-2.0
// The door is a generated view. It is never the source of truth, and never hand-edited.
package render

import (
	"fmt"
	"regexp"
	"strings"
	"unicode/utf16"

	"github.com/RagnarPitla/agent-fridge/internal/brand"
	"github.com/RagnarPitla/agent-fridge/internal/fsx"
	"github.com/RagnarPitla/agent-fridge/internal/jsonx"
	"github.com/RagnarPitla/agent-fridge/internal/store"
	"github.com/RagnarPitla/agent-fridge/internal/util"
)

func length(s string) int { return len(utf16.Encode([]rune(s))) }

func pad(s string, n int) string {
	if l := length(s); l < n {
		return s + strings.Repeat(" ", n-l)
	}
	return s
}

func cut(s string, n int) string {
	units := utf16.Encode([]rune(s))
	if len(units) > n {
		return string(utf16.Decode(units[:n-1])) + "~"
	}
	return s
}

// Snapshot is the shape every view renders from.
func Snapshot(ws *store.Workspace) jsonx.Obj {
	claims := jsonx.Arr{}
	for _, d := range store.ListClaims(ws, true) {
		if d.Stale {
			continue
		}
		c := d.Claim
		var branch any
		if b := c.Str("labels.branch"); b != "" {
			branch = b
		}
		var pid any
		if p, ok := c.Get("process.pid").(float64); ok {
			pid = p
		}
		claims = append(claims, jsonx.Obj{
			"id":          c.Str("id"),
			"actorName":   c.Str("actorName"),
			"vendor":      c.Str("vendor"),
			"mode":        c.Str("mode"),
			"task":        c.Get("task"),
			"include":     toArr(c.Strings("scope.include")),
			"exclude":     toArr(c.Strings("scope.exclude")),
			"files":       float64(len(c.ArrAt("scope.materialized"))),
			"branch":      branch,
			"expiresAt":   d.EffectiveExpiresAt,
			"expiresInMs": float64(d.ExpiresInMs),
			"pid":         pid,
			"state":       c.Str("state"),
		})
	}
	notes := jsonx.Arr{}
	for _, n := range store.ReadNotes(ws, store.NoteFilter{Limit: 5}) {
		notes = append(notes, jsonx.Obj{
			"ts": n.Str("ts"), "actorName": n.Str("actorName"),
			"type": n.Str("type"), "summary": n.Get("summary"),
		})
	}
	return jsonx.Obj{
		"workspaceId": ws.Config.Str("workspaceId"),
		"generatedAt": util.Now(),
		"claims":      claims,
		"waiting":     float64(len(fsx.ListJSON(ws.Paths.Queue))),
		"notes":       notes,
	}
}

func toArr(in []string) jsonx.Arr {
	out := jsonx.Arr{}
	for _, s := range in {
		out = append(out, s)
	}
	return out
}

// StateKey hashes everything that matters with wall-clock noise removed, so
// that --check answers "is this view stale?" and not "did a second pass?".
func StateKey(ws *store.Workspace) string {
	s := Snapshot(ws)
	claims := jsonx.Arr{}
	for _, raw := range s.ArrAt("claims") {
		c, _ := raw.(jsonx.Obj)
		copyOf := c.Clone()
		delete(copyOf, "expiresInMs")
		claims = append(claims, copyOf)
	}
	return util.ShortHash(jsonx.Stable(jsonx.Obj{
		"workspaceId": s.Str("workspaceId"),
		"waiting":     s.Num("waiting"),
		"claims":      claims,
		"notes":       s.ArrAt("notes"),
	}))
}

// StateKeyRE finds the recorded state hash inside a generated view.
var StateKeyRE = regexp.MustCompile(`state:([0-9a-f]{12})`)

// Drift is decided by the recorded state key, never by diffing rendered text.
func Drift(ws *store.Workspace, text string) (drift bool, found, want string) {
	m := StateKeyRE.FindStringSubmatch(text)
	want = StateKey(ws)
	if m == nil {
		return true, "", want
	}
	return m[1] != want, m[1], want
}

// Door renders .fridge/DOOR.md.
func Door(ws *store.Workspace) string {
	s := Snapshot(ws)
	lines := []string{}
	lines = append(lines, fmt.Sprintf("<!-- GENERATED by %s %s at %s state:%s", brand.Package, brand.Version, s.Str("generatedAt"), StateKey(ws)))
	lines = append(lines, "     Source of truth: .fridge/. DO NOT EDIT. Regenerate with: fridge render -->")
	lines = append(lines, "# The door")
	lines = append(lines, "")
	claims := s.ArrAt("claims")
	lines = append(lines, fmt.Sprintf("Fridge `%s` | %d chore(s) claimed | %s waiting",
		s.Str("workspaceId"), len(claims), jsonx.FormatNumber(s.Num("waiting"))))
	lines = append(lines, "")
	lines = append(lines, "## Claimed right now")
	lines = append(lines, "")
	if len(claims) == 0 {
		lines = append(lines, "Nothing is claimed. The door is clear.")
	} else {
		lines = append(lines, "| Card | Who | Mode | Scope | Doing | Back by |")
		lines = append(lines, "|---|---|---|---|---|---|")
		for _, raw := range claims {
			c, _ := raw.(jsonx.Obj)
			quoted := []string{}
			for _, p := range c.Strings("include") {
				quoted = append(quoted, "`"+p+"`")
			}
			task := c.Str("task")
			if task == "" {
				task = "-"
			}
			lines = append(lines, fmt.Sprintf("| `%s` | %s (%s) | %s | %s | %s | in %s |",
				c.Str("id"), c.Str("actorName"), c.Str("vendor"), c.Str("mode"),
				strings.Join(quoted, ", "), task, util.HumanMs(int64(c.Num("expiresInMs")))))
		}
	}
	lines = append(lines, "")
	lines = append(lines, "## Last 5 notes")
	lines = append(lines, "")
	notes := s.ArrAt("notes")
	if len(notes) == 0 {
		lines = append(lines, "No notes pinned yet.")
	} else {
		for _, raw := range notes {
			n, _ := raw.(jsonx.Obj)
			lines = append(lines, fmt.Sprintf("- %s %s `%s` %s", n.Str("ts"), n.Str("actorName"), n.Str("type"), n.Str("summary")))
		}
	}
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// StatusText renders the terminal status view.
func StatusText(ws *store.Workspace, mine string, wide bool) string {
	s := Snapshot(ws)
	claims := jsonx.Arr{}
	for _, raw := range s.ArrAt("claims") {
		c, _ := raw.(jsonx.Obj)
		if mine != "" && c.Str("actorName") != mine {
			continue
		}
		claims = append(claims, c)
	}
	out := []string{}
	out = append(out, fmt.Sprintf("fridge %s  %d claimed  %s waiting",
		s.Str("workspaceId"), len(claims), jsonx.FormatNumber(s.Num("waiting"))))
	out = append(out, "")
	if len(claims) == 0 {
		out = append(out, "Nothing is claimed. The door is clear.")
	} else {
		w := 24
		if wide {
			w = 40
		}
		out = append(out, pad("CARD", 32)+pad("WHO", 16)+pad("MODE", 10)+pad("SCOPE", w)+pad("BACK BY", 10)+"TASK")
		for _, raw := range claims {
			c, _ := raw.(jsonx.Obj)
			task := c.Str("task")
			if task == "" {
				task = "-"
			}
			taskWidth := 40
			if wide {
				taskWidth = 80
			}
			out = append(out, pad(c.Str("id"), 32)+pad(cut(c.Str("actorName"), 15), 16)+pad(c.Str("mode"), 10)+
				pad(cut(strings.Join(c.Strings("include"), ","), w-1), w)+
				pad(util.HumanMs(int64(c.Num("expiresInMs"))), 10)+cut(task, taskWidth))
		}
	}
	notes := s.ArrAt("notes")
	if len(notes) > 0 {
		out = append(out, "")
		out = append(out, "recent notes:")
		for _, raw := range notes {
			n, _ := raw.(jsonx.Obj)
			out = append(out, fmt.Sprintf("  %s  %s %s %s", n.Str("ts"),
				pad(cut(n.Str("actorName"), 14), 15), pad(n.Str("type"), 18), cut(n.Str("summary"), 70)))
		}
	}
	return strings.Join(out, "\n")
}

// Auto keeps the door fresh after anything that changes state. A stale view
// must never fail a real operation, so failures are swallowed.
func Auto(ws *store.Workspace) bool {
	if !ws.Config.Bool("door.autoRender") {
		return false
	}
	if err := fsx.WriteAtomic(ws.Paths.Door, Door(ws), ws.Paths.Tmp); err != nil {
		return false
	}
	return true
}
